// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MVC10.Models;

public partial class Movie
{
    public int MovieId { get; set; }

    public int DirectorId { get; set; }

    public string Color { get; set; }

    public int? NumCriticForReviews { get; set; }

    public int? Duration { get; set; }

    public int? DirectorFacebookLikes { get; set; }

    public int? Actor3FacebookLikes { get; set; }

    public string Actor2Name { get; set; }

    public int? Actor1FacebookLikes { get; set; }

    public long? Gross { get; set; }

    public string Genres { get; set; }

    public string Actor1Name { get; set; }

    public string MovieTitle { get; set; }

    public int? NumVotedUsers { get; set; }

    public int? CastTotalFacebookLikes { get; set; }

    public string Actor3Name { get; set; }

    public int? FacenumberInPoster { get; set; }

    public string PlotKeywords { get; set; }

    public string MovieImdbLink { get; set; }

    public int? NumUserForReviews { get; set; }

    public string Language { get; set; }

    public string Country { get; set; }

    public string ContentRating { get; set; }

    public long? Budget { get; set; }

    public int? TitleYear { get; set; }

    public int? Actor2FacebookLikes { get; set; }

    public decimal? ImdbScore { get; set; }

    public decimal? AspectRatio { get; set; }

    public int? MovieFacebookLikes { get; set; }

    public virtual Director Director { get; set; }
}